services:
  - type: web
    name: marcusina-backend
    env: node
    plan: free
    rootDir: Telemedicine-nodejs-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
