databases:
  - name: marcusina-db
    plan: free

services:
  - type: web
    name: marcusina-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MIGRATION_DATABASE_URL
        fromDatabase:
          name: marcusina-db
          property: connectionString
      - key: APP_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
