databases:
  - name: marcusina-db
    plan: free

services:
  - type: web
    name: marcusina-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: MIGRATION_DATABASE_URL
        fromDatabase:
          name: marcusina-db
          property: connectionString
      - key: APP_DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: "465"
      - key: EMAIL_HOST_SECURE
        value: "true"
      - key: EMAIL_HOST_USERNAME
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
